version: "2"
services:
  framadate-db:
    container_name: framadate-db
    image: mysql:5.7
    volumes:
      - ./volumes/db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=motdepasseroot
      - MYSQL_USER=framadate
      - MYSQL_PASSWORD=framadatedbpassword
      - MYSQL_DATABASE=framadate
    restart: always

  framadate:
    container_name: framadate
    image: tcitworld/framadate:development
    links:
      - framadate-db:mysql
    ports:
      - 80:80
    environment:
      - DOMAIN=localhost
      - APP_NAME=Framadate
      - ADMIN_MAIL=mon@email.fr
      - MYSQL_USER=framadate
      - MYSQL_PASSWORD=framadatedbpassword
      - MYSQL_DB=framadate
      - MYSQL_HOST=mysql
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=adminpassword
      - DISABLE_SMTP=true
    restart: always
